export const gameModel = {
    'title': "",
    'name': "",
    'category': "Action RPG",
    'subtitle': "",
    'description': "",
    'description2': "",
    'featureImage': "ps_logo.png",
    'featureVideo': "ps_logo.png",
    'gameBoxImage': "ps_logo.png",
    'trailerLink': "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    'price': "69.99",
    'backgroundImage': "ps_logo.png",
    'gameLogo': "ps_logo.png",
    'favorites': "",
    'developer': "",
    'publisher': "",
    'year': "",
    'screenshots': "ps_logo.png",
    'isDark': false,
    'isFeatured': false,
}