export const gameModel = {
    'title': "",
    'name': "",
    'category': "Action RPG",
    'subtitle': "",
    'description': "",
    'description2': "",
    'featureImage': "",
    'featureVideo': "",
    'gameBoxImage': "",
    'trailerLink': "",
    'price': "",
    'backgroundImage': "",
    'gameLogo': "",
    'favorites': "",
    'developer': "",
    'publisher': "",
    'year': "",
    'screenshots': "",
    'isDark': false,
    'isFeatured': false,
}